### ISSUE TITLE
Create a binary release

### ISSUE THREAD

**Issue by BlueMM75** [AqlaSolutions/FirefoxHistoryMerger#1]
Like similar other projects on GitHub, this request is for releases to be tagged, and a binary to be included in that release.

My scenario: I don't have access to VS to compile it myself, but would like to experiment in merging places db's, before upgrading to Firefox Quantum v57 (which I think changes the schema - not sure).

Therefore I would like a windows binary added to the project, for downloading & execution.

**Comment by AqlaSolutions** [comment]
Hi, thanks for interesting in my project. Since it doesn't have any UI (I didn't really want to invest in this short-term project) and its setup is hardcoded (input, output) now you need VS to change the paths.

**Comment by BlueMM75** [comment]
Makes sense.
Given I'm experimenting & presume this will be a once off, I personally would be happy with hardcoded paths (as I can always create the same paths). I would love a binary to see if it will be useful, since I have not VS (& not enough room to install).

**Comment by AqlaSolutions** [comment]
@BlueMM75 ok, I added binaries
